name: Elixir CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Erlang/OTP and Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: '24.0'
          elixir-version: '1.12.3'
          ImageOS: 'ubuntu20'
      - name: Build
        run: mix compile
